#! bin/sh
xsetroot -cursor_name left_ptr
xrdb merge ~/.Xresources
xset +fp ~/.fonts/misc &
feh --bg-scale ~/.config/bspwm/wallpaper.png &
polybar -c ~/.config/polybar/bspbar.ini topbar &
sxhkd &
exec bspwm
