#! /bin/sh

# BASIC SETUP
sxhkd &
picom --experimental-backend &
xsetroot -cursor_name left_ptr &
wal -n -i ~/space.jpeg &
polybar -q -r -c ~/.config/polybar/walbar.ini &
xset +fp ~/.fonts/misc/ &
feh --bg-scale ~/space.jpeg &
dunst -conf ~/.cache/wal/dunstrc &


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

# Rosé pine 
#bspc config focused_border_color "#9ccfd8"
#bspc config normal_border_color "#6e6a86"

# Workpaces
bspc monitor -d 1 2 3 4

# General Config
bspc config border_radius        0
bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pamac state=floating
bspc rule -a Thunar state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

